import type { SeededRng } from '../rng';
import { clamp, ideologicalDistance, MAX_IDEOLOGICAL_DISTANCE } from '../ideology';
import type {
  CareerCitizenInitiativeRecord,
  CareerLocalRaceRecord,
  CareerNominationRecord,
  CareerStage,
  CareerState,
  EducationTrack,
  IdeologyPosition,
  Party,
  PoliticianAttributes,
} from '../models/types';

/**
 * CAREER MODE — the pre-game life sim. Pure and content-free like every
 * other engine system: name pools, country/party rosters, and anything
 * else content-shaped are generated by the caller (engine/index.ts) and
 * passed in, never imported here directly.
 *
 * Career turns are seasons, not the main game's weeks — a full run (17 to
 * a national nomination) plays out over roughly 20-40 turns rather than
 * hundreds.
 */

export const CAREER_TURNS_PER_YEAR = 4;
export const CAREER_STARTING_AGE = 17;

export function computeCareerAge(turn: number): number {
  return CAREER_STARTING_AGE + turn / CAREER_TURNS_PER_YEAR;
}

const ATTRIBUTE_KEYS: (keyof PoliticianAttributes)[] = [
  'charisma',
  'intellect',
  'integrity',
  'network',
  'mediaSavvy',
];

function addAttributes(base: PoliticianAttributes, delta: Partial<PoliticianAttributes>): PoliticianAttributes {
  const next = { ...base };
  for (const key of ATTRIBUTE_KEYS) {
    next[key] = clamp(next[key] + (delta[key] ?? 0), 1, 10);
  }
  return next;
}

/** Derives the display stage from what's actually been achieved, rather than tracking it as separate mutable state. */
export function computeCareerStage(state: CareerState): CareerStage {
  if (state.nominationHistory.some((n) => n.selected)) return 'graduated';
  if (state.regionalSeatWon) return 'regional_officeholder';
  if (state.localSeatWon) return 'local_officeholder';
  if (state.partyId) return 'party_volunteer';
  if (state.jobId) return 'working';
  return 'student';
}

function withStage(state: CareerState): CareerState {
  return { ...state, stage: computeCareerStage(state) };
}

/**
 * Every new career starts a real backbencher's nowhere: low attributes
 * (with a little seeded jitter so no two careers begin identically), a
 * near-centrist ideology that hasn't been shaped by anything yet, and
 * next to no money.
 */
export function createCareer(seed: number, rng: SeededRng, name: string, countryOptionId: string): CareerState {
  const jitter = () => (rng.next() - 0.5) * 2; // -1..1

  const state: CareerState = {
    seed,
    rngState: rng.getState(),
    turn: 0,
    name,
    countryOptionId,
    stage: 'student',
    attributes: {
      charisma: clamp(2 + jitter(), 1, 10),
      intellect: clamp(2 + jitter(), 1, 10),
      integrity: clamp(3 + jitter(), 1, 10),
      network: clamp(1 + jitter(), 1, 10),
      mediaSavvy: clamp(1 + jitter(), 1, 10),
    },
    ideology: { economic: clamp(jitter() * 20, -100, 100), social: clamp(jitter() * 20, -100, 100) },
    money: 50,
    educationTrack: null,
    educationTurnsRemaining: 0,
    completedEducationTracks: [],
    jobId: null,
    partyId: null,
    foundedParty: null,
    partyStanding: 0,
    localSeatWon: false,
    localRaceHistory: [],
    regionalSeatWon: false,
    regionalRaceHistory: [],
    nominationHistory: [],
    civicRecord: 0,
    citizenInitiatives: [],
    campaignMomentum: 0,
    partyOfficer: false,
    eventLog: [],
  };
  return withStage(state);
}

/**
 * EDUCATION
 */

export interface EducationTrackConfig {
  id: EducationTrack;
  label: string;
  durationTurns: number;
  costPerTurn: number;
  attributeGainPerTurn: Partial<PoliticianAttributes>;
  completionBonus: Partial<PoliticianAttributes>;
  /** Some tracks build on an earlier one — law school assumes an undergraduate degree, not a blank slate. */
  prerequisite?: EducationTrack;
}

export const EDUCATION_TRACKS: Record<EducationTrack, EducationTrackConfig> = {
  community_college: {
    id: 'community_college',
    label: 'Community College',
    durationTurns: 4,
    costPerTurn: 15,
    attributeGainPerTurn: { intellect: 0.3, network: 0.1 },
    completionBonus: { intellect: 0.5 },
  },
  trade_apprenticeship: {
    id: 'trade_apprenticeship',
    label: 'Trade Apprenticeship',
    durationTurns: 6,
    costPerTurn: 8,
    attributeGainPerTurn: { network: 0.3, charisma: 0.1 },
    completionBonus: { network: 0.5 },
  },
  state_university: {
    id: 'state_university',
    label: 'State University',
    durationTurns: 8,
    costPerTurn: 25,
    attributeGainPerTurn: { intellect: 0.4, mediaSavvy: 0.1 },
    completionBonus: { intellect: 1 },
  },
  law_school: {
    id: 'law_school',
    label: 'Law School',
    durationTurns: 12,
    costPerTurn: 40,
    attributeGainPerTurn: { intellect: 0.5, integrity: 0.1 },
    completionBonus: { intellect: 1.5, integrity: 0.5 },
    prerequisite: 'state_university',
  },
};

export function canStartEducation(state: CareerState, track: EducationTrack): boolean {
  if (state.educationTrack) return false;
  const config = EDUCATION_TRACKS[track];
  if (config.prerequisite && !state.completedEducationTracks.includes(config.prerequisite)) return false;
  return true;
}

export function startEducation(state: CareerState, track: EducationTrack): CareerState {
  if (!canStartEducation(state, track)) return state;
  const config = EDUCATION_TRACKS[track];
  return withStage({ ...state, educationTrack: track, educationTurnsRemaining: config.durationTurns });
}

/**
 * JOBS
 */

export interface JobConfig {
  id: string;
  title: string;
  incomePerTurn: number;
  attributeGainPerTurn: Partial<PoliticianAttributes>;
  requiresEducation?: EducationTrack;
  requiresParty?: boolean;
}

export const JOB_LISTINGS: JobConfig[] = [
  {
    id: 'retail_clerk',
    title: 'Retail Clerk',
    incomePerTurn: 30,
    attributeGainPerTurn: { charisma: 0.1, network: 0.05 },
  },
  {
    id: 'campaign_intern',
    title: 'Campaign Intern',
    incomePerTurn: 15,
    attributeGainPerTurn: { network: 0.3, mediaSavvy: 0.15, charisma: 0.1 },
    requiresParty: true,
  },
  {
    id: 'paralegal',
    title: 'Paralegal',
    incomePerTurn: 70,
    attributeGainPerTurn: { intellect: 0.2, integrity: 0.1 },
    requiresEducation: 'state_university',
  },
  {
    id: 'small_business_owner',
    title: 'Small Business Owner',
    incomePerTurn: 100,
    attributeGainPerTurn: { charisma: 0.2, network: 0.2 },
    requiresEducation: 'trade_apprenticeship',
  },
  {
    id: 'junior_associate',
    title: 'Junior Associate',
    incomePerTurn: 130,
    attributeGainPerTurn: { intellect: 0.15, integrity: 0.15, network: 0.1 },
    requiresEducation: 'law_school',
  },
];

export function canApplyForJob(state: CareerState, jobId: string): boolean {
  const job = JOB_LISTINGS.find((j) => j.id === jobId);
  if (!job) return false;
  if (job.requiresEducation && !state.completedEducationTracks.includes(job.requiresEducation)) return false;
  if (job.requiresParty && !state.partyId) return false;
  return true;
}

export function applyForJob(state: CareerState, jobId: string): CareerState {
  if (!canApplyForJob(state, jobId)) return state;
  return withStage({ ...state, jobId });
}

/**
 * PARTY INVOLVEMENT
 */

export function joinParty(state: CareerState, partyId: string): CareerState {
  if (state.partyId) return state;
  return withStage({ ...state, partyId, partyStanding: Math.max(state.partyStanding, 5) });
}

/**
 * Rather than joining an existing party, found a brand-new one built
 * around the player's own current ideology — no one to answer to means
 * an immediate 100 standing (you're unquestionably its leader), but no
 * existing machine or membership to inherit either.
 */
export function foundOwnParty(state: CareerState, partyId: string, name: string): CareerState {
  if (state.partyId) return state;
  const foundedParty: Party = { id: partyId, name, ideology: { ...state.ideology }, seats: 0, factions: [] };
  return withStage({ ...state, partyId, foundedParty, partyStanding: 100 });
}

export type PartyWorkOutcomeTier = 'strong' | 'solid' | 'setback';

export interface PartyWorkOutcome {
  outcome: PartyWorkOutcomeTier;
  standingDelta: number;
}

function computeOrganizingSkill(attributes: PoliticianAttributes): number {
  return clamp((attributes.charisma + attributes.network + attributes.integrity) / 30, 0, 1);
}

const PARTY_WORK_STRONG_DELTA = 8;
const PARTY_WORK_SOLID_DELTA = 3;
const PARTY_WORK_SETBACK_DELTA = -2;

/** Canvassing, phone-banking, running local events — the grind that actually builds standing within the party. */
export function doPartyWork(state: CareerState, rng: SeededRng): { state: CareerState; outcome: PartyWorkOutcome } {
  if (!state.partyId) {
    return { state, outcome: { outcome: 'solid', standingDelta: 0 } };
  }

  const skill = computeOrganizingSkill(state.attributes);
  const pStrong = 0.15 + skill * 0.35;
  const pSetback = 0.25 - skill * 0.2;
  const roll = rng.next();

  let outcome: PartyWorkOutcomeTier;
  let standingDelta: number;
  if (roll < pStrong) {
    outcome = 'strong';
    standingDelta = PARTY_WORK_STRONG_DELTA;
  } else if (roll < 1 - pSetback) {
    outcome = 'solid';
    standingDelta = PARTY_WORK_SOLID_DELTA;
  } else {
    outcome = 'setback';
    standingDelta = PARTY_WORK_SETBACK_DELTA;
  }

  const partyStanding = clamp(state.partyStanding + standingDelta, 0, 100);
  return {
    state: withStage({ ...state, partyStanding, rngState: rng.getState() }),
    outcome: { outcome, standingDelta },
  };
}

/**
 * PARTY LEADERSHIP — the difference between being well-liked in the party
 * and actually holding a lever inside its machine. A one-shot bid, gated
 * on standing built up through doPartyWork, that installs the player as a
 * local party officer on success: a permanent standing floor and a real
 * nomination-odds bonus, not just another temporary boost.
 */

export const PARTY_OFFICER_STANDING_REQUIREMENT = 60;
const PARTY_OFFICER_STANDING_FLOOR = 40;
const PARTY_LEADERSHIP_BID_SETBACK = -10;

export function canSeekPartyLeadership(state: CareerState): boolean {
  return !!state.partyId && !state.partyOfficer && state.partyStanding >= PARTY_OFFICER_STANDING_REQUIREMENT;
}

export interface PartyLeadershipOutcome {
  won: boolean;
  probability: number;
}

/** Probability leans heavily on standing (the delegates who'll actually vote for you), with network and charisma as secondary factors. */
export function computePartyLeadershipProbability(state: CareerState): number {
  const standingTerm = (state.partyStanding - 50) / 50;
  const attributeTerm = (state.attributes.network + state.attributes.charisma - 10) / 10;
  const score = 1.6 * standingTerm + 0.6 * attributeTerm;
  return clamp(sigmoid(score), 0.05, 0.9);
}

export function attemptPartyLeadershipBid(
  state: CareerState,
  rng: SeededRng
): { state: CareerState; outcome: PartyLeadershipOutcome | null } {
  if (!canSeekPartyLeadership(state)) {
    return { state, outcome: null };
  }

  const probability = computePartyLeadershipProbability(state);
  const won = rng.next() < probability;
  const partyStanding = won ? state.partyStanding : clamp(state.partyStanding + PARTY_LEADERSHIP_BID_SETBACK, 0, 100);

  return {
    state: withStage({ ...state, partyOfficer: state.partyOfficer || won, partyStanding, rngState: rng.getState() }),
    outcome: { won, probability },
  };
}

/**
 * REAL CAMPAIGN MECHANICS — short-lived buzz built between race attempts.
 * Canvassing is cheap and leans on charisma/network; a media blitz is
 * expensive and leans on media savvy/charisma. Both feed campaignMomentum,
 * which factors into computePersonalAppeal for local/regional races and
 * the national nomination alike.
 */

export type CampaignActivityType = 'canvass' | 'media_blitz';

export interface CampaignActivityConfig {
  id: CampaignActivityType;
  label: string;
  cost: number;
}

export const CAMPAIGN_ACTIVITIES: Record<CampaignActivityType, CampaignActivityConfig> = {
  canvass: { id: 'canvass', label: 'Canvass the District', cost: 15 },
  media_blitz: { id: 'media_blitz', label: 'Run a Media Blitz', cost: 80 },
};

function computeCampaignSkill(attributes: PoliticianAttributes, activityType: CampaignActivityType): number {
  if (activityType === 'media_blitz') {
    return clamp((attributes.mediaSavvy + attributes.charisma) / 20, 0, 1);
  }
  return clamp((attributes.charisma + attributes.network) / 20, 0, 1);
}

export type CampaignActivityOutcomeTier = 'strong' | 'solid' | 'setback';

export interface CampaignActivityOutcome {
  activityType: CampaignActivityType;
  outcome: CampaignActivityOutcomeTier;
  momentumDelta: number;
}

const CAMPAIGN_STRONG_DELTA = 14;
const CAMPAIGN_SOLID_DELTA = 6;
const CAMPAIGN_SETBACK_DELTA = -4;

export function canRunCampaignActivity(state: CareerState, activityType: CampaignActivityType): boolean {
  return state.money >= CAMPAIGN_ACTIVITIES[activityType].cost;
}

export function runCampaignActivity(
  state: CareerState,
  activityType: CampaignActivityType,
  rng: SeededRng
): { state: CareerState; outcome: CampaignActivityOutcome | null } {
  if (!canRunCampaignActivity(state, activityType)) {
    return { state, outcome: null };
  }

  const config = CAMPAIGN_ACTIVITIES[activityType];
  const skill = computeCampaignSkill(state.attributes, activityType);
  const pStrong = 0.15 + skill * 0.35;
  const pSetback = 0.25 - skill * 0.2;
  const roll = rng.next();

  let outcome: CampaignActivityOutcomeTier;
  let momentumDelta: number;
  if (roll < pStrong) {
    outcome = 'strong';
    momentumDelta = CAMPAIGN_STRONG_DELTA;
  } else if (roll < 1 - pSetback) {
    outcome = 'solid';
    momentumDelta = CAMPAIGN_SOLID_DELTA;
  } else {
    outcome = 'setback';
    momentumDelta = CAMPAIGN_SETBACK_DELTA;
  }

  const campaignMomentum = clamp(state.campaignMomentum + momentumDelta, 0, 100);
  return {
    state: withStage({ ...state, money: state.money - config.cost, campaignMomentum, rngState: rng.getState() }),
    outcome: { activityType, outcome, momentumDelta },
  };
}

/**
 * LOCAL COUNCIL RACE
 */

export interface LocalRaceOutcome {
  won: boolean;
  playerShare: number;
  opponentNames: string[];
  opponentShares: number[];
}

const LOCAL_RACE_CAMPAIGN_COST = 60;

/**
 * Ideology fit and personal appeal (attributes + party standing + a public
 * civic record + short-lived campaign momentum) all matter — neither alone
 * is enough. civicRecord and campaignMomentum are optional so callers that
 * predate those systems still compile; they carry real weight once a
 * player has actually built either up.
 */
export function computePersonalAppeal(
  attributes: PoliticianAttributes,
  partyStanding: number,
  civicRecord = 0,
  campaignMomentum = 0
): number {
  const attributeAppeal = (attributes.charisma + attributes.mediaSavvy + attributes.network) / 30;
  const standingAppeal = partyStanding / 100;
  const civicAppeal = civicRecord / 100;
  const momentumAppeal = campaignMomentum / 100;
  return clamp(attributeAppeal * 0.45 + standingAppeal * 0.3 + civicAppeal * 0.1 + momentumAppeal * 0.15, 0.05, 1);
}

/**
 * A real, self-contained mini-election: 1-3 generated rivals (names
 * supplied by the caller — career.ts stays content-free) contest a
 * randomly-seeded local electorate. The player's score blends how well
 * their ideology fits that electorate with their personal appeal; rivals
 * get a flat generic baseline, since they're not being played, not
 * simulated as full politicians. Requires a real campaign fund, same as
 * any other resource-gated action in this engine.
 */
export function attemptLocalRace(
  state: CareerState,
  rivalNames: string[],
  rng: SeededRng
): { state: CareerState; outcome: LocalRaceOutcome | null } {
  if (state.money < LOCAL_RACE_CAMPAIGN_COST) {
    return { state, outcome: null };
  }

  const localElectorateIdeology: IdeologyPosition = {
    economic: (rng.next() - 0.5) * 160,
    social: (rng.next() - 0.5) * 160,
  };

  const playerAlignment = 1 - ideologicalDistance(state.ideology, localElectorateIdeology) / MAX_IDEOLOGICAL_DISTANCE;
  const playerAppeal = computePersonalAppeal(state.attributes, state.partyStanding, state.civicRecord, state.campaignMomentum);
  const playerScore = Math.max(0.02, playerAlignment * 0.5 + playerAppeal * 0.5 + (rng.next() - 0.5) * 0.15);
  const rivalScores = rivalNames.map(() => Math.max(0.02, 0.3 + rng.next() * 0.4));

  const total = playerScore + rivalScores.reduce((a, b) => a + b, 0);
  const playerShare = playerScore / total;
  const opponentShares = rivalScores.map((s) => s / total);
  const won = rivalScores.every((s) => s < playerScore);

  const record: CareerLocalRaceRecord = { turn: state.turn, won, playerShare, opponentNames: rivalNames };

  return {
    state: withStage({
      ...state,
      money: state.money - LOCAL_RACE_CAMPAIGN_COST,
      localSeatWon: state.localSeatWon || won,
      localRaceHistory: [...state.localRaceHistory, record],
      rngState: rng.getState(),
    }),
    outcome: { won, playerShare, opponentNames: rivalNames, opponentShares },
  };
}

/**
 * REGIONAL RACE — the next rung up the ladder. A state/regional
 * legislature seat, deliberately gated on having won a local seat first:
 * the career has to climb the ladder in order, not skip straight to a
 * bigger office. Tougher, better-funded rivals than the local race.
 */

const REGIONAL_RACE_CAMPAIGN_COST = 150;

export function canAttemptRegionalRace(state: CareerState): boolean {
  return state.localSeatWon && state.money >= REGIONAL_RACE_CAMPAIGN_COST;
}

export function attemptRegionalRace(
  state: CareerState,
  rivalNames: string[],
  rng: SeededRng
): { state: CareerState; outcome: LocalRaceOutcome | null } {
  if (!canAttemptRegionalRace(state)) {
    return { state, outcome: null };
  }

  const regionalElectorateIdeology: IdeologyPosition = {
    economic: (rng.next() - 0.5) * 160,
    social: (rng.next() - 0.5) * 160,
  };

  const playerAlignment = 1 - ideologicalDistance(state.ideology, regionalElectorateIdeology) / MAX_IDEOLOGICAL_DISTANCE;
  const playerAppeal = computePersonalAppeal(state.attributes, state.partyStanding, state.civicRecord, state.campaignMomentum);
  const playerScore = Math.max(0.02, playerAlignment * 0.5 + playerAppeal * 0.5 + (rng.next() - 0.5) * 0.15);
  // Tougher field than a local race — better-funded, more experienced rivals.
  const rivalScores = rivalNames.map(() => Math.max(0.02, 0.4 + rng.next() * 0.45));

  const total = playerScore + rivalScores.reduce((a, b) => a + b, 0);
  const playerShare = playerScore / total;
  const opponentShares = rivalScores.map((s) => s / total);
  const won = rivalScores.every((s) => s < playerScore);

  const record: CareerLocalRaceRecord = { turn: state.turn, won, playerShare, opponentNames: rivalNames };

  return {
    state: withStage({
      ...state,
      money: state.money - REGIONAL_RACE_CAMPAIGN_COST,
      regionalSeatWon: state.regionalSeatWon || won,
      regionalRaceHistory: [...state.regionalRaceHistory, record],
      rngState: rng.getState(),
    }),
    outcome: { won, playerShare, opponentNames: rivalNames, opponentShares },
  };
}

/**
 * LOCAL GOVERNANCE — what actually holding office is for. Available only
 * once a seat (local or regional) is won, this is the governing
 * counterpart to doPartyWork: constituency service, committee work, and
 * legislating build a public record (civicRecord) rather than party
 * standing. Governing skill draws on integrity/intellect/network, distinct
 * from the charisma-led organizing skill that powers party work.
 */

export type GovernanceOutcomeTier = 'strong' | 'solid' | 'setback';

export interface GovernanceOutcome {
  outcome: GovernanceOutcomeTier;
  civicRecordDelta: number;
}

function computeGoverningSkill(attributes: PoliticianAttributes): number {
  return clamp((attributes.integrity + attributes.intellect + attributes.network) / 30, 0, 1);
}

const GOVERNANCE_STRONG_DELTA = 8;
const GOVERNANCE_SOLID_DELTA = 3;
const GOVERNANCE_SETBACK_DELTA = -2;

export function canGovernLocally(state: CareerState): boolean {
  return state.localSeatWon || state.regionalSeatWon;
}

export function doLocalGovernance(state: CareerState, rng: SeededRng): { state: CareerState; outcome: GovernanceOutcome | null } {
  if (!canGovernLocally(state)) {
    return { state, outcome: null };
  }

  const skill = computeGoverningSkill(state.attributes);
  const pStrong = 0.15 + skill * 0.35;
  const pSetback = 0.25 - skill * 0.2;
  const roll = rng.next();

  let outcome: GovernanceOutcomeTier;
  let civicRecordDelta: number;
  if (roll < pStrong) {
    outcome = 'strong';
    civicRecordDelta = GOVERNANCE_STRONG_DELTA;
  } else if (roll < 1 - pSetback) {
    outcome = 'solid';
    civicRecordDelta = GOVERNANCE_SOLID_DELTA;
  } else {
    outcome = 'setback';
    civicRecordDelta = GOVERNANCE_SETBACK_DELTA;
  }

  const civicRecord = clamp(state.civicRecord + civicRecordDelta, 0, 100);
  return {
    state: withStage({ ...state, civicRecord, rngState: rng.getState() }),
    outcome: { outcome, civicRecordDelta },
  };
}

/**
 * CITIZEN PETITIONS — lawmaking without a seat or even a party. A local
 * ballot initiative filed straight to the public, resolved immediately
 * against a randomly-seeded local electorate, the same shape as
 * attemptLocalRace. No stage requirement: this is deliberately available
 * from turn zero, before joining a party or winning anything.
 */

export interface CitizenInitiativeOutcome {
  passed: boolean;
  supportShare: number;
}

export const CITIZEN_INITIATIVE_COST = 20;

export function canProposeCitizenInitiative(state: CareerState): boolean {
  return state.money >= CITIZEN_INITIATIVE_COST;
}

const CITIZEN_INITIATIVE_PASS_STANDING = 10;
const CITIZEN_INITIATIVE_FAIL_STANDING = -3;

export function attemptCitizenInitiative(
  state: CareerState,
  title: string,
  stance: IdeologyPosition,
  rng: SeededRng
): { state: CareerState; outcome: CitizenInitiativeOutcome | null } {
  if (!canProposeCitizenInitiative(state)) {
    return { state, outcome: null };
  }

  const localOpinion: IdeologyPosition = {
    economic: (rng.next() - 0.5) * 160,
    social: (rng.next() - 0.5) * 160,
  };
  const alignment = 1 - ideologicalDistance(stance, localOpinion) / MAX_IDEOLOGICAL_DISTANCE;
  const organizingSkill = clamp((state.attributes.mediaSavvy + state.attributes.network + state.attributes.charisma) / 30, 0, 1);
  const supportShare = clamp(alignment * 0.65 + organizingSkill * 0.25 + (rng.next() - 0.5) * 0.2, 0.02, 0.98);
  const passed = supportShare >= 0.5;

  const record: CareerCitizenInitiativeRecord = { turn: state.turn, title, passed, supportShare };
  const civicRecord = clamp(
    state.civicRecord + (passed ? CITIZEN_INITIATIVE_PASS_STANDING : CITIZEN_INITIATIVE_FAIL_STANDING),
    0,
    100
  );

  return {
    state: withStage({
      ...state,
      money: state.money - CITIZEN_INITIATIVE_COST,
      civicRecord,
      citizenInitiatives: [...state.citizenInitiatives, record],
      rngState: rng.getState(),
    }),
    outcome: { passed, supportShare },
  };
}

/**
 * NATIONAL NOMINATION
 */

export interface NominationOutcome {
  selected: boolean;
  probability: number;
}

function sigmoid(x: number): number {
  return 1 / (1 + Math.exp(-x));
}

/**
 * A probabilistic gate rather than a simulated vote — this represents the
 * party leadership's own closed-door decision, not a poll of anyone the
 * player interacts with. Party standing dominates; having actually held
 * office is a real, separate boost that grows with how high up the ladder
 * that office was; a party leadership post and fresh campaign momentum
 * both matter too, but personal attributes matter least of all.
 */
export function computeNominationProbability(state: CareerState): number {
  const standingTerm = (state.partyStanding - 50) / 50;
  const seatBonus = (state.localSeatWon ? 0.4 : 0) + (state.regionalSeatWon ? 0.8 : 0);
  const attributeTerm = (state.attributes.charisma + state.attributes.integrity + state.attributes.intellect - 15) / 15;
  const civicTerm = (state.civicRecord - 50) / 50;
  const officerBonus = state.partyOfficer ? 1 : 0;
  const momentumTerm = (state.campaignMomentum - 50) / 50;
  const score =
    1.4 * standingTerm + 1.2 * seatBonus + 0.8 * attributeTerm + 0.4 * civicTerm + 0.7 * officerBonus + 0.3 * momentumTerm;
  return clamp(sigmoid(score), 0.02, 0.95);
}

export function attemptNationalNomination(
  state: CareerState,
  rng: SeededRng
): { state: CareerState; outcome: NominationOutcome } {
  if (!state.partyId) {
    return { state, outcome: { selected: false, probability: 0 } };
  }

  const probability = computeNominationProbability(state);
  const selected = rng.next() < probability;
  const record: CareerNominationRecord = { turn: state.turn, selected, probability };

  return {
    state: withStage({ ...state, nominationHistory: [...state.nominationHistory, record], rngState: rng.getState() }),
    outcome: { selected, probability },
  };
}

export function isGraduated(state: CareerState): boolean {
  return state.nominationHistory.some((n) => n.selected);
}

/**
 * TURN ADVANCEMENT
 */

const PARTY_STANDING_DECAY_RATE = 0.04;
const CAMPAIGN_MOMENTUM_DECAY_RATE = 0.2;
const IDEOLOGY_DRIFT_RATE = 0.08;
const LOCAL_OFFICE_STIPEND = 20;
const REGIONAL_OFFICE_STIPEND = 50;

/**
 * Advances one career season: education and employment both apply their
 * per-turn attribute gains and costs/income (a player can work through
 * school — both run at once, not exclusively), unspent party standing
 * decays a little without reinforcement (the same "needs upkeep" shape as
 * interest-group disposition), and ideology drifts gradually toward the
 * joined party's own position — who you organize alongside shapes what
 * you come to believe, not an instant conversion.
 */
export function advanceCareerTurn(state: CareerState, parties: Party[]): CareerState {
  let attributes = state.attributes;
  let money = state.money;
  let educationTrack = state.educationTrack;
  let educationTurnsRemaining = state.educationTurnsRemaining;
  let completedEducationTracks = state.completedEducationTracks;
  const eventLog = [...state.eventLog];

  if (educationTrack) {
    const config = EDUCATION_TRACKS[educationTrack];
    attributes = addAttributes(attributes, config.attributeGainPerTurn);
    money = Math.max(0, money - config.costPerTurn);
    educationTurnsRemaining -= 1;
    if (educationTurnsRemaining <= 0) {
      attributes = addAttributes(attributes, config.completionBonus);
      completedEducationTracks = [...completedEducationTracks, educationTrack];
      eventLog.push({
        turn: state.turn + 1,
        title: `Graduated: ${config.label}`,
        description: `Completed the ${config.label} track.`,
      });
      educationTrack = null;
      educationTurnsRemaining = 0;
    }
  }

  if (state.jobId) {
    const job = JOB_LISTINGS.find((j) => j.id === state.jobId);
    if (job) {
      attributes = addAttributes(attributes, job.attributeGainPerTurn);
      money += job.incomePerTurn;
    }
  }

  // An officeholder's stipend — regional supersedes local rather than stacking, since winning a regional seat means moving up, not moonlighting both.
  if (state.regionalSeatWon) {
    money += REGIONAL_OFFICE_STIPEND;
  } else if (state.localSeatWon) {
    money += LOCAL_OFFICE_STIPEND;
  }

  let partyStanding = state.partyId ? state.partyStanding * (1 - PARTY_STANDING_DECAY_RATE) : state.partyStanding;
  if (state.partyOfficer) {
    partyStanding = Math.max(partyStanding, PARTY_OFFICER_STANDING_FLOOR);
  }
  const civicRecord = state.civicRecord * (1 - PARTY_STANDING_DECAY_RATE);
  const campaignMomentum = state.campaignMomentum * (1 - CAMPAIGN_MOMENTUM_DECAY_RATE);

  let ideology = state.ideology;
  const party = state.foundedParty ?? (state.partyId ? parties.find((p) => p.id === state.partyId) : undefined);
  if (party) {
    ideology = {
      economic: ideology.economic + (party.ideology.economic - ideology.economic) * IDEOLOGY_DRIFT_RATE,
      social: ideology.social + (party.ideology.social - ideology.social) * IDEOLOGY_DRIFT_RATE,
    };
  }

  return withStage({
    ...state,
    turn: state.turn + 1,
    attributes,
    money,
    educationTrack,
    educationTurnsRemaining,
    completedEducationTracks,
    partyStanding,
    civicRecord,
    campaignMomentum,
    ideology,
    eventLog,
  });
}

/**
 * GRADUATION
 */

export interface CareerGraduationPayload {
  playerName: string;
  playerAttributes: PoliticianAttributes;
  playerIdeology: IdeologyPosition;
  playerPartyId: string;
  countryOptionId: string;
  /** 0..1, derived from final party standing — used to give the new MP a warmer starting reception than the random default. */
  standingBonus: number;
  /** Set when playerPartyId refers to a self-founded party rather than one of the country's starter parties — the caller must add it to the roster before creating the game. */
  founderPartyDefinition: Party | null;
}

/** Null unless the career has actually cleared a national nomination. */
export function buildGraduationPayload(state: CareerState): CareerGraduationPayload | null {
  if (!isGraduated(state) || !state.partyId) return null;
  return {
    playerName: state.name,
    playerAttributes: {
      charisma: Math.round(state.attributes.charisma),
      intellect: Math.round(state.attributes.intellect),
      integrity: Math.round(state.attributes.integrity),
      network: Math.round(state.attributes.network),
      mediaSavvy: Math.round(state.attributes.mediaSavvy),
    },
    playerIdeology: state.ideology,
    playerPartyId: state.partyId,
    countryOptionId: state.countryOptionId,
    standingBonus: clamp(state.partyStanding / 100, 0, 1),
    founderPartyDefinition: state.foundedParty,
  };
}
