import type { SeededRng } from '../rng';
import { clamp, ideologicalDistance, MAX_IDEOLOGICAL_DISTANCE } from '../ideology';
import type {
  CareerLocalRaceRecord,
  CareerNominationRecord,
  CareerStage,
  CareerState,
  EducationTrack,
  IdeologyPosition,
  Party,
  PoliticianAttributes,
} from '../models/types';

/**
 * CAREER MODE — the pre-game life sim. Pure and content-free like every
 * other engine system: name pools, country/party rosters, and anything
 * else content-shaped are generated by the caller (engine/index.ts) and
 * passed in, never imported here directly.
 *
 * Career turns are seasons, not the main game's weeks — a full run (17 to
 * a national nomination) plays out over roughly 20-40 turns rather than
 * hundreds.
 */

export const CAREER_TURNS_PER_YEAR = 4;
export const CAREER_STARTING_AGE = 17;

export function computeCareerAge(turn: number): number {
  return CAREER_STARTING_AGE + turn / CAREER_TURNS_PER_YEAR;
}

const ATTRIBUTE_KEYS: (keyof PoliticianAttributes)[] = [
  'charisma',
  'intellect',
  'integrity',
  'network',
  'mediaSavvy',
];

function addAttributes(base: PoliticianAttributes, delta: Partial<PoliticianAttributes>): PoliticianAttributes {
  const next = { ...base };
  for (const key of ATTRIBUTE_KEYS) {
    next[key] = clamp(next[key] + (delta[key] ?? 0), 1, 10);
  }
  return next;
}

/** Derives the display stage from what's actually been achieved, rather than tracking it as separate mutable state. */
export function computeCareerStage(state: CareerState): CareerStage {
  if (state.nominationHistory.some((n) => n.selected)) return 'graduated';
  if (state.localSeatWon) return 'local_officeholder';
  if (state.partyId) return 'party_volunteer';
  if (state.jobId) return 'working';
  return 'student';
}

function withStage(state: CareerState): CareerState {
  return { ...state, stage: computeCareerStage(state) };
}

/**
 * Every new career starts a real backbencher's nowhere: low attributes
 * (with a little seeded jitter so no two careers begin identically), a
 * near-centrist ideology that hasn't been shaped by anything yet, and
 * next to no money.
 */
export function createCareer(seed: number, rng: SeededRng, name: string, countryOptionId: string): CareerState {
  const jitter = () => (rng.next() - 0.5) * 2; // -1..1

  const state: CareerState = {
    seed,
    rngState: rng.getState(),
    turn: 0,
    name,
    countryOptionId,
    stage: 'student',
    attributes: {
      charisma: clamp(2 + jitter(), 1, 10),
      intellect: clamp(2 + jitter(), 1, 10),
      integrity: clamp(3 + jitter(), 1, 10),
      network: clamp(1 + jitter(), 1, 10),
      mediaSavvy: clamp(1 + jitter(), 1, 10),
    },
    ideology: { economic: clamp(jitter() * 20, -100, 100), social: clamp(jitter() * 20, -100, 100) },
    money: 50,
    educationTrack: null,
    educationTurnsRemaining: 0,
    completedEducationTracks: [],
    jobId: null,
    partyId: null,
    partyStanding: 0,
    localSeatWon: false,
    localRaceHistory: [],
    nominationHistory: [],
    eventLog: [],
  };
  return withStage(state);
}

/**
 * EDUCATION
 */

export interface EducationTrackConfig {
  id: EducationTrack;
  label: string;
  durationTurns: number;
  costPerTurn: number;
  attributeGainPerTurn: Partial<PoliticianAttributes>;
  completionBonus: Partial<PoliticianAttributes>;
  /** Some tracks build on an earlier one — law school assumes an undergraduate degree, not a blank slate. */
  prerequisite?: EducationTrack;
}

export const EDUCATION_TRACKS: Record<EducationTrack, EducationTrackConfig> = {
  community_college: {
    id: 'community_college',
    label: 'Community College',
    durationTurns: 4,
    costPerTurn: 15,
    attributeGainPerTurn: { intellect: 0.3, network: 0.1 },
    completionBonus: { intellect: 0.5 },
  },
  trade_apprenticeship: {
    id: 'trade_apprenticeship',
    label: 'Trade Apprenticeship',
    durationTurns: 6,
    costPerTurn: 8,
    attributeGainPerTurn: { network: 0.3, charisma: 0.1 },
    completionBonus: { network: 0.5 },
  },
  state_university: {
    id: 'state_university',
    label: 'State University',
    durationTurns: 8,
    costPerTurn: 25,
    attributeGainPerTurn: { intellect: 0.4, mediaSavvy: 0.1 },
    completionBonus: { intellect: 1 },
  },
  law_school: {
    id: 'law_school',
    label: 'Law School',
    durationTurns: 12,
    costPerTurn: 40,
    attributeGainPerTurn: { intellect: 0.5, integrity: 0.1 },
    completionBonus: { intellect: 1.5, integrity: 0.5 },
    prerequisite: 'state_university',
  },
};

export function canStartEducation(state: CareerState, track: EducationTrack): boolean {
  if (state.educationTrack) return false;
  const config = EDUCATION_TRACKS[track];
  if (config.prerequisite && !state.completedEducationTracks.includes(config.prerequisite)) return false;
  return true;
}

export function startEducation(state: CareerState, track: EducationTrack): CareerState {
  if (!canStartEducation(state, track)) return state;
  const config = EDUCATION_TRACKS[track];
  return withStage({ ...state, educationTrack: track, educationTurnsRemaining: config.durationTurns });
}

/**
 * JOBS
 */

export interface JobConfig {
  id: string;
  title: string;
  incomePerTurn: number;
  attributeGainPerTurn: Partial<PoliticianAttributes>;
  requiresEducation?: EducationTrack;
  requiresParty?: boolean;
}

export const JOB_LISTINGS: JobConfig[] = [
  {
    id: 'retail_clerk',
    title: 'Retail Clerk',
    incomePerTurn: 30,
    attributeGainPerTurn: { charisma: 0.1, network: 0.05 },
  },
  {
    id: 'campaign_intern',
    title: 'Campaign Intern',
    incomePerTurn: 15,
    attributeGainPerTurn: { network: 0.3, mediaSavvy: 0.15, charisma: 0.1 },
    requiresParty: true,
  },
  {
    id: 'paralegal',
    title: 'Paralegal',
    incomePerTurn: 70,
    attributeGainPerTurn: { intellect: 0.2, integrity: 0.1 },
    requiresEducation: 'state_university',
  },
  {
    id: 'small_business_owner',
    title: 'Small Business Owner',
    incomePerTurn: 100,
    attributeGainPerTurn: { charisma: 0.2, network: 0.2 },
    requiresEducation: 'trade_apprenticeship',
  },
  {
    id: 'junior_associate',
    title: 'Junior Associate',
    incomePerTurn: 130,
    attributeGainPerTurn: { intellect: 0.15, integrity: 0.15, network: 0.1 },
    requiresEducation: 'law_school',
  },
];

export function canApplyForJob(state: CareerState, jobId: string): boolean {
  const job = JOB_LISTINGS.find((j) => j.id === jobId);
  if (!job) return false;
  if (job.requiresEducation && !state.completedEducationTracks.includes(job.requiresEducation)) return false;
  if (job.requiresParty && !state.partyId) return false;
  return true;
}

export function applyForJob(state: CareerState, jobId: string): CareerState {
  if (!canApplyForJob(state, jobId)) return state;
  return withStage({ ...state, jobId });
}

/**
 * PARTY INVOLVEMENT
 */

export function joinParty(state: CareerState, partyId: string): CareerState {
  if (state.partyId) return state;
  return withStage({ ...state, partyId, partyStanding: Math.max(state.partyStanding, 5) });
}

export type PartyWorkOutcomeTier = 'strong' | 'solid' | 'setback';

export interface PartyWorkOutcome {
  outcome: PartyWorkOutcomeTier;
  standingDelta: number;
}

function computeOrganizingSkill(attributes: PoliticianAttributes): number {
  return clamp((attributes.charisma + attributes.network + attributes.integrity) / 30, 0, 1);
}

const PARTY_WORK_STRONG_DELTA = 8;
const PARTY_WORK_SOLID_DELTA = 3;
const PARTY_WORK_SETBACK_DELTA = -2;

/** Canvassing, phone-banking, running local events — the grind that actually builds standing within the party. */
export function doPartyWork(state: CareerState, rng: SeededRng): { state: CareerState; outcome: PartyWorkOutcome } {
  if (!state.partyId) {
    return { state, outcome: { outcome: 'solid', standingDelta: 0 } };
  }

  const skill = computeOrganizingSkill(state.attributes);
  const pStrong = 0.15 + skill * 0.35;
  const pSetback = 0.25 - skill * 0.2;
  const roll = rng.next();

  let outcome: PartyWorkOutcomeTier;
  let standingDelta: number;
  if (roll < pStrong) {
    outcome = 'strong';
    standingDelta = PARTY_WORK_STRONG_DELTA;
  } else if (roll < 1 - pSetback) {
    outcome = 'solid';
    standingDelta = PARTY_WORK_SOLID_DELTA;
  } else {
    outcome = 'setback';
    standingDelta = PARTY_WORK_SETBACK_DELTA;
  }

  const partyStanding = clamp(state.partyStanding + standingDelta, 0, 100);
  return {
    state: withStage({ ...state, partyStanding, rngState: rng.getState() }),
    outcome: { outcome, standingDelta },
  };
}

/**
 * LOCAL COUNCIL RACE
 */

export interface LocalRaceOutcome {
  won: boolean;
  playerShare: number;
  opponentNames: string[];
  opponentShares: number[];
}

const LOCAL_RACE_CAMPAIGN_COST = 60;

/** Ideology fit and personal appeal (attributes + party standing) both matter — neither alone is enough. */
export function computePersonalAppeal(attributes: PoliticianAttributes, partyStanding: number): number {
  const attributeAppeal = (attributes.charisma + attributes.mediaSavvy + attributes.network) / 30;
  const standingAppeal = partyStanding / 100;
  return clamp(attributeAppeal * 0.6 + standingAppeal * 0.4, 0.05, 1);
}

/**
 * A real, self-contained mini-election: 1-3 generated rivals (names
 * supplied by the caller — career.ts stays content-free) contest a
 * randomly-seeded local electorate. The player's score blends how well
 * their ideology fits that electorate with their personal appeal; rivals
 * get a flat generic baseline, since they're not being played, not
 * simulated as full politicians. Requires a real campaign fund, same as
 * any other resource-gated action in this engine.
 */
export function attemptLocalRace(
  state: CareerState,
  rivalNames: string[],
  rng: SeededRng
): { state: CareerState; outcome: LocalRaceOutcome | null } {
  if (state.money < LOCAL_RACE_CAMPAIGN_COST) {
    return { state, outcome: null };
  }

  const localElectorateIdeology: IdeologyPosition = {
    economic: (rng.next() - 0.5) * 160,
    social: (rng.next() - 0.5) * 160,
  };

  const playerAlignment = 1 - ideologicalDistance(state.ideology, localElectorateIdeology) / MAX_IDEOLOGICAL_DISTANCE;
  const playerAppeal = computePersonalAppeal(state.attributes, state.partyStanding);
  const playerScore = Math.max(0.02, playerAlignment * 0.5 + playerAppeal * 0.5 + (rng.next() - 0.5) * 0.15);
  const rivalScores = rivalNames.map(() => Math.max(0.02, 0.3 + rng.next() * 0.4));

  const total = playerScore + rivalScores.reduce((a, b) => a + b, 0);
  const playerShare = playerScore / total;
  const opponentShares = rivalScores.map((s) => s / total);
  const won = rivalScores.every((s) => s < playerScore);

  const record: CareerLocalRaceRecord = { turn: state.turn, won, playerShare, opponentNames: rivalNames };

  return {
    state: withStage({
      ...state,
      money: state.money - LOCAL_RACE_CAMPAIGN_COST,
      localSeatWon: state.localSeatWon || won,
      localRaceHistory: [...state.localRaceHistory, record],
      rngState: rng.getState(),
    }),
    outcome: { won, playerShare, opponentNames: rivalNames, opponentShares },
  };
}

/**
 * NATIONAL NOMINATION
 */

export interface NominationOutcome {
  selected: boolean;
  probability: number;
}

function sigmoid(x: number): number {
  return 1 / (1 + Math.exp(-x));
}

/**
 * A probabilistic gate rather than a simulated vote — this represents the
 * party leadership's own closed-door decision, not a poll of anyone the
 * player interacts with. Party standing dominates; having actually won a
 * local seat is a real, separate boost; personal attributes matter but
 * least of the three.
 */
export function computeNominationProbability(state: CareerState): number {
  const standingTerm = (state.partyStanding - 50) / 50;
  const seatBonus = state.localSeatWon ? 1 : 0;
  const attributeTerm = (state.attributes.charisma + state.attributes.integrity + state.attributes.intellect - 15) / 15;
  const score = 1.4 * standingTerm + 1.2 * seatBonus + 0.8 * attributeTerm;
  return clamp(sigmoid(score), 0.02, 0.95);
}

export function attemptNationalNomination(
  state: CareerState,
  rng: SeededRng
): { state: CareerState; outcome: NominationOutcome } {
  if (!state.partyId) {
    return { state, outcome: { selected: false, probability: 0 } };
  }

  const probability = computeNominationProbability(state);
  const selected = rng.next() < probability;
  const record: CareerNominationRecord = { turn: state.turn, selected, probability };

  return {
    state: withStage({ ...state, nominationHistory: [...state.nominationHistory, record], rngState: rng.getState() }),
    outcome: { selected, probability },
  };
}

export function isGraduated(state: CareerState): boolean {
  return state.nominationHistory.some((n) => n.selected);
}

/**
 * TURN ADVANCEMENT
 */

const PARTY_STANDING_DECAY_RATE = 0.04;
const IDEOLOGY_DRIFT_RATE = 0.08;

/**
 * Advances one career season: education and employment both apply their
 * per-turn attribute gains and costs/income (a player can work through
 * school — both run at once, not exclusively), unspent party standing
 * decays a little without reinforcement (the same "needs upkeep" shape as
 * interest-group disposition), and ideology drifts gradually toward the
 * joined party's own position — who you organize alongside shapes what
 * you come to believe, not an instant conversion.
 */
export function advanceCareerTurn(state: CareerState, parties: Party[]): CareerState {
  let attributes = state.attributes;
  let money = state.money;
  let educationTrack = state.educationTrack;
  let educationTurnsRemaining = state.educationTurnsRemaining;
  let completedEducationTracks = state.completedEducationTracks;
  const eventLog = [...state.eventLog];

  if (educationTrack) {
    const config = EDUCATION_TRACKS[educationTrack];
    attributes = addAttributes(attributes, config.attributeGainPerTurn);
    money = Math.max(0, money - config.costPerTurn);
    educationTurnsRemaining -= 1;
    if (educationTurnsRemaining <= 0) {
      attributes = addAttributes(attributes, config.completionBonus);
      completedEducationTracks = [...completedEducationTracks, educationTrack];
      eventLog.push({
        turn: state.turn + 1,
        title: `Graduated: ${config.label}`,
        description: `Completed the ${config.label} track.`,
      });
      educationTrack = null;
      educationTurnsRemaining = 0;
    }
  }

  if (state.jobId) {
    const job = JOB_LISTINGS.find((j) => j.id === state.jobId);
    if (job) {
      attributes = addAttributes(attributes, job.attributeGainPerTurn);
      money += job.incomePerTurn;
    }
  }

  const partyStanding = state.partyId ? state.partyStanding * (1 - PARTY_STANDING_DECAY_RATE) : state.partyStanding;

  let ideology = state.ideology;
  const party = state.partyId ? parties.find((p) => p.id === state.partyId) : undefined;
  if (party) {
    ideology = {
      economic: ideology.economic + (party.ideology.economic - ideology.economic) * IDEOLOGY_DRIFT_RATE,
      social: ideology.social + (party.ideology.social - ideology.social) * IDEOLOGY_DRIFT_RATE,
    };
  }

  return withStage({
    ...state,
    turn: state.turn + 1,
    attributes,
    money,
    educationTrack,
    educationTurnsRemaining,
    completedEducationTracks,
    partyStanding,
    ideology,
    eventLog,
  });
}

/**
 * GRADUATION
 */

export interface CareerGraduationPayload {
  playerName: string;
  playerAttributes: PoliticianAttributes;
  playerIdeology: IdeologyPosition;
  playerPartyId: string;
  countryOptionId: string;
  /** 0..1, derived from final party standing — used to give the new MP a warmer starting reception than the random default. */
  standingBonus: number;
}

/** Null unless the career has actually cleared a national nomination. */
export function buildGraduationPayload(state: CareerState): CareerGraduationPayload | null {
  if (!isGraduated(state) || !state.partyId) return null;
  return {
    playerName: state.name,
    playerAttributes: {
      charisma: Math.round(state.attributes.charisma),
      intellect: Math.round(state.attributes.intellect),
      integrity: Math.round(state.attributes.integrity),
      network: Math.round(state.attributes.network),
      mediaSavvy: Math.round(state.attributes.mediaSavvy),
    },
    playerIdeology: state.ideology,
    playerPartyId: state.partyId,
    countryOptionId: state.countryOptionId,
    standingBonus: clamp(state.partyStanding / 100, 0, 1),
  };
}
