import { clamp } from '../ideology';
import type { EconomyDelta, EnergyPolicyLevel, EnvironmentState, Factory, Mine } from '../models/types';

/**
 * ENVIRONMENT & CLIMATE — pollution is generated by the industrial base you
 * actually built (mines and factories, scaled by tier — see mining.ts and
 * manufacturing.ts), not an abstract slider, offset by whatever share of
 * the energy mix is renewable. High pollution taxes growth directly and
 * raises the odds of a natural-disaster crisis event (see
 * events.ts's computeEventWeight, which reads environment.pollutionIndex).
 */

const EMISSIONS_PER_MINE_TIER = 1.5;
const EMISSIONS_PER_FACTORY_TIER = 2;

/** Real emissions generated this turn, driven entirely by the tiers of mines/factories actually built — idle (empty) industry emits nothing. */
export function computeIndustrialEmissions(mines: Mine[], factories: Factory[]): number {
  const mineEmissions = mines.reduce((sum, m) => sum + m.tier * EMISSIONS_PER_MINE_TIER, 0);
  const factoryEmissions = factories.reduce((sum, f) => sum + f.tier * EMISSIONS_PER_FACTORY_TIER, 0);
  return mineEmissions + factoryEmissions;
}

const POLLUTION_EMISSIONS_SCALE = 0.5;
const POLLUTION_NATURAL_DECAY = 0.5;
const RENEWABLE_OFFSET_SCALE = 0.3;

/** This turn's emissions push pollution up, a renewable-share offset and a small constant natural-absorption decay pull it back down. */
export function advancePollutionIndex(environment: EnvironmentState, emissions: number): EnvironmentState {
  const renewableOffset = (environment.renewableShare / 100) * RENEWABLE_OFFSET_SCALE * emissions;
  const netChange = emissions * POLLUTION_EMISSIONS_SCALE - renewableOffset - POLLUTION_NATURAL_DECAY;
  return { ...environment, pollutionIndex: clamp(environment.pollutionIndex + netChange, 0, 100) };
}

const ENERGY_POLICY_TARGET: Record<EnergyPolicyLevel, number> = {
  fossil_heavy: 15,
  balanced: 45,
  renewable_focus: 80,
};

export function setEnergyPolicy(environment: EnvironmentState, policy: EnergyPolicyLevel): EnvironmentState {
  return { ...environment, energyPolicy: policy };
}

const RENEWABLE_BASE_RATE = 0.03;
const RENEWABLE_CAPABILITY_RATE_SCALE = 0.0015;

function moveToward(current: number, target: number, rate: number): number {
  return current + (target - current) * rate;
}

/** Renewable share drifts toward whatever the current energy policy implies, faster the more green-infrastructure capability is invested. */
export function advanceRenewableShare(environment: EnvironmentState): EnvironmentState {
  const target = ENERGY_POLICY_TARGET[environment.energyPolicy];
  const rate = RENEWABLE_BASE_RATE + environment.greenInvestmentCapability * RENEWABLE_CAPABILITY_RATE_SCALE;
  return { ...environment, renewableShare: clamp(moveToward(environment.renewableShare, target, rate), 0, 100) };
}

export type GreenInvestmentTier = 'modest' | 'major';

export interface GreenInvestmentConfig {
  budgetCost: number;
  capabilityGain: number;
}

export const GREEN_INVESTMENT_TIERS: Record<GreenInvestmentTier, GreenInvestmentConfig> = {
  modest: { budgetCost: -0.25, capabilityGain: 8 },
  major: { budgetCost: -0.75, capabilityGain: 22 },
};

export interface GreenInvestmentResult {
  environment: EnvironmentState;
  economyEffect: EconomyDelta;
}

export function investInGreenInfrastructure(environment: EnvironmentState, tier: GreenInvestmentTier): GreenInvestmentResult {
  const config = GREEN_INVESTMENT_TIERS[tier];
  return {
    environment: { ...environment, greenInvestmentCapability: clamp(environment.greenInvestmentCapability + config.capabilityGain, 0, 100) },
    economyEffect: { budgetBalance: config.budgetCost },
  };
}

const MAX_POLLUTION_GDP_DRAG = 0.4;

/** A real, if modest, growth tax from high pollution — health costs, lost productivity. */
export function computePollutionEconomyEffect(pollutionIndex: number): EconomyDelta {
  return { gdpGrowth: -(pollutionIndex / 100) * MAX_POLLUTION_GDP_DRAG };
}

const MAX_DISASTER_RISK_MULTIPLIER_BONUS = 1.5;

/** >=1 — how much higher pollution makes a natural-disaster crisis event this turn, for events.ts's computeEventWeight to apply. */
export function computeDisasterRiskMultiplier(pollutionIndex: number): number {
  return 1 + (pollutionIndex / 100) * MAX_DISASTER_RISK_MULTIPLIER_BONUS;
}
