import type { EnergyPolicyLevel } from '../../engine';
import { useStatecraftStore } from '../store';

export function EnvironmentPanel() {
  const game = useStatecraftStore((s) => s.game);
  const setEnergyPolicyAction = useStatecraftStore((s) => s.setEnergyPolicyAction);
  const investInGreenInfrastructureAction = useStatecraftStore((s) => s.investInGreenInfrastructureAction);

  if (!game) return null;

  const environment = game.environment;

  return (
    <section className="panel">
      <div className="panel-header">
        <h2>Environment &amp; Climate</h2>
        <span className="muted">Pollution generated by the mines and factories you've actually built</span>
      </div>

      <div className="indicator-grid">
        <div className="indicator">
          <div className="indicator-label">Pollution Index</div>
          <div className="indicator-value">{environment.pollutionIndex.toFixed(1)}</div>
        </div>
        <div className="indicator">
          <div className="indicator-label">Renewable Share</div>
          <div className="indicator-value">{environment.renewableShare.toFixed(1)}%</div>
        </div>
        <div className="indicator">
          <div className="indicator-label">Green Investment Capability</div>
          <div className="indicator-value">{environment.greenInvestmentCapability.toFixed(0)}</div>
        </div>
      </div>

      <div className="custom-bill-form">
        <label>
          Energy Policy
          <select value={environment.energyPolicy} onChange={(e) => setEnergyPolicyAction(e.target.value as EnergyPolicyLevel)}>
            <option value="fossil_heavy">Fossil-Heavy</option>
            <option value="balanced">Balanced</option>
            <option value="renewable_focus">Renewable-Focus</option>
          </select>
        </label>
      </div>
      <div className="bill-actions">
        <button onClick={() => investInGreenInfrastructureAction('modest')}>Invest in Green Infrastructure (Modest)</button>
        <button onClick={() => investInGreenInfrastructureAction('major')}>Invest in Green Infrastructure (Major)</button>
      </div>
      <p className="muted">
        High pollution taxes growth directly and raises the odds of a natural-disaster crisis. Renewable share drifts
        toward whatever your energy policy implies, faster the more green-infrastructure capability you've invested.
      </p>
    </section>
  );
}
