import type { CrisisEventDef } from '../../engine/systems/events';

/**
 * The base weighted event table. Actual per-turn weights are adjusted
 * against live game state by engine/systems/events.ts (a fragile economy
 * raises economic_shock odds, an unresolved scandal raises scandal odds,
 * low approval raises civil_unrest odds).
 */
export const CRISIS_TABLE: CrisisEventDef[] = [
  {
    id: 'recession-warning',
    category: 'economic_shock',
    title: 'Recession Warning',
    description: 'Economists warn of a coming downturn as growth stalls.',
    baseWeight: 6,
    economyEffect: { gdpGrowth: -0.8, unemployment: 0.5 },
    playerApprovalEffect: -5,
  },
  {
    id: 'market-rally',
    category: 'economic_shock',
    title: 'Surprise Market Rally',
    description: 'A wave of investor confidence sends markets higher.',
    baseWeight: 4,
    economyEffect: { gdpGrowth: 0.6 },
    playerApprovalEffect: 3,
  },
  {
    id: 'flooding',
    category: 'natural_disaster',
    title: 'Severe Flooding',
    description: 'Heavy rains flood the river delta, displacing thousands.',
    baseWeight: 5,
    economyEffect: { gdpGrowth: -0.5, budgetBalance: -0.4 },
    playerApprovalEffect: -4,
  },
  {
    id: 'earthquake',
    category: 'natural_disaster',
    title: 'Earthquake Strikes the Coast',
    description: 'A moderate earthquake damages infrastructure along the coast.',
    baseWeight: 3,
    economyEffect: { gdpGrowth: -0.7, budgetBalance: -0.6 },
    playerApprovalEffect: -6,
  },
  {
    id: 'border-incident',
    category: 'international_incident',
    title: 'Border Skirmish',
    description: 'Tensions flare after a border patrol confrontation.',
    baseWeight: 4,
    foreignRelationEffect: { counterpartId: 'nordholm', delta: -15 },
    playerApprovalEffect: -3,
  },
  {
    id: 'diplomatic-breakthrough',
    category: 'international_incident',
    title: 'Diplomatic Breakthrough',
    description: 'A surprise summit produces a goodwill agreement.',
    baseWeight: 3,
    foreignRelationEffect: { counterpartId: 'valcressa', delta: 12 },
    playerApprovalEffect: 4,
  },
  {
    id: 'general-strike',
    category: 'civil_unrest',
    title: 'General Strike',
    description: 'Unions call a nationwide strike over stagnant wages.',
    baseWeight: 5,
    economyEffect: { gdpGrowth: -0.4 },
    playerApprovalEffect: -6,
  },
  {
    id: 'street-protests',
    category: 'civil_unrest',
    title: 'Street Protests',
    description: 'Demonstrators gather in the capital demanding reform.',
    baseWeight: 5,
    playerApprovalEffect: -8,
  },
  {
    id: 'flu-outbreak',
    category: 'public_health',
    title: 'Seasonal Flu Outbreak',
    description: 'A severe flu season strains hospitals nationwide.',
    baseWeight: 4,
    economyEffect: { unemployment: 0.3, gdpGrowth: -0.2 },
    playerApprovalEffect: -3,
  },
  {
    id: 'vaccine-success',
    category: 'public_health',
    title: 'Vaccination Drive Succeeds',
    description: 'A national vaccination campaign exceeds its targets.',
    baseWeight: 3,
    playerApprovalEffect: 5,
  },
  {
    id: 'cyber-attack',
    category: 'security_incident',
    title: 'Cyberattack on Government Systems',
    description: "Hackers breach a government ministry's network.",
    baseWeight: 4,
    economyEffect: { budgetBalance: -0.3 },
    playerApprovalEffect: -5,
  },
  {
    id: 'foiled-plot',
    category: 'security_incident',
    title: 'Security Services Foil Plot',
    description: 'Intelligence services announce a foiled attack.',
    baseWeight: 3,
    playerApprovalEffect: 4,
  },
  {
    id: 'press-leak',
    category: 'scandal',
    title: 'Leaked Documents Raise Questions',
    description: 'A leaked memo raises fresh questions about government dealings.',
    baseWeight: 3,
    playerApprovalEffect: -6,
  },
  {
    id: 'currency-swings',
    category: 'economic_shock',
    title: 'Currency Volatility Rattles Markets',
    description: 'Sharp swings in the exchange rate unsettle importers and exporters alike.',
    baseWeight: 3,
    economyEffect: { inflation: 0.5, gdpGrowth: -0.2 },
    playerApprovalEffect: -2,
  },
  {
    id: 'export-contract',
    category: 'economic_shock',
    title: 'Major Export Contract Signed',
    description: 'A landmark export deal promises a boost to manufacturing.',
    baseWeight: 3,
    economyEffect: { gdpGrowth: 0.5, budgetBalance: 0.2 },
    playerApprovalEffect: 3,
  },
  {
    id: 'drought',
    category: 'natural_disaster',
    title: 'Prolonged Drought Hits Agriculture',
    description: 'A dry season strains farming regions and pushes up food prices.',
    baseWeight: 4,
    economyEffect: { inflation: 0.4, gdpGrowth: -0.3 },
    playerApprovalEffect: -4,
  },
  {
    id: 'wildfires',
    category: 'natural_disaster',
    title: 'Wildfires Sweep Rural Districts',
    description: 'Fast-moving wildfires force evacuations across several districts.',
    baseWeight: 3,
    economyEffect: { budgetBalance: -0.5 },
    playerApprovalEffect: -5,
  },
  {
    id: 'trade-dispute',
    category: 'international_incident',
    title: 'Trade Dispute Escalates',
    description: 'Tariff threats sour relations with a key trading partner.',
    baseWeight: 3,
    foreignRelationEffect: { counterpartId: 'suvenya', delta: -12 },
    economyEffect: { gdpGrowth: -0.2 },
    playerApprovalEffect: -2,
  },
  {
    id: 'joint-exercise',
    category: 'international_incident',
    title: 'Joint Military Exercise Praised',
    description: 'A successful joint exercise strengthens ties with an ally.',
    baseWeight: 2,
    foreignRelationEffect: { counterpartId: 'draventia', delta: 10 },
    playerApprovalEffect: 2,
  },
  {
    id: 'campus-protests',
    category: 'civil_unrest',
    title: 'University Campuses Erupt in Protest',
    description: 'Students walk out over tuition and cost-of-living concerns.',
    baseWeight: 3,
    playerApprovalEffect: -4,
  },
  {
    id: 'community-mediation',
    category: 'civil_unrest',
    title: 'Community Mediation Defuses Tensions',
    description: 'Local leaders broker a truce after weeks of unrest.',
    baseWeight: 2,
    playerApprovalEffect: 3,
  },
  {
    id: 'hospital-crisis',
    category: 'public_health',
    title: 'Hospital Overcrowding Crisis',
    description: 'Emergency rooms nationwide report dangerous overcrowding.',
    baseWeight: 3,
    economyEffect: { budgetBalance: -0.3 },
    playerApprovalEffect: -5,
  },
  {
    id: 'medical-breakthrough',
    category: 'public_health',
    title: 'Researchers Announce Medical Breakthrough',
    description: 'A domestic research team publishes a widely praised treatment advance.',
    baseWeight: 2,
    playerApprovalEffect: 4,
  },
  {
    id: 'arms-seizure',
    category: 'security_incident',
    title: 'Major Arms Seizure at the Border',
    description: 'Customs agents intercept a large illegal arms shipment.',
    baseWeight: 3,
    playerApprovalEffect: 3,
  },
  {
    id: 'prison-unrest',
    category: 'security_incident',
    title: 'Unrest Reported at a Major Prison',
    description: 'Overcrowding sparks a standoff at a national penitentiary.',
    baseWeight: 2,
    economyEffect: { budgetBalance: -0.2 },
    playerApprovalEffect: -3,
  },
  {
    id: 'donor-scandal',
    category: 'scandal',
    title: 'Undisclosed Donor Ties Revealed',
    description: 'Reporters uncover an undisclosed financial relationship with a major donor.',
    baseWeight: 3,
    playerApprovalEffect: -7,
  },
  {
    id: 'nepotism-claims',
    category: 'scandal',
    title: 'Nepotism Claims Rock a Ministry',
    description: 'A ministry is accused of steering appointments to well-connected relatives.',
    baseWeight: 2,
    playerApprovalEffect: -5,
  },
  {
    id: 'housing-bubble-warning',
    category: 'economic_shock',
    title: 'Economists Warn of a Housing Bubble',
    description: 'Runaway home prices in major cities draw warnings of a coming correction.',
    baseWeight: 3,
    economyEffect: { gdpGrowth: -0.2, inflation: 0.3 },
    playerApprovalEffect: -2,
  },
  {
    id: 'foreign-investment-surge',
    category: 'economic_shock',
    title: 'Foreign Investment Surges',
    description: 'A wave of new foreign direct investment lifts confidence in the economy.',
    baseWeight: 3,
    economyEffect: { gdpGrowth: 0.5, budgetBalance: 0.2 },
    playerApprovalEffect: 3,
  },
  {
    id: 'supply-chain-shock',
    category: 'economic_shock',
    title: 'Supply Chain Bottleneck Hits Manufacturers',
    description: 'Shipping delays and parts shortages stall factory output nationwide.',
    baseWeight: 4,
    economyEffect: { gdpGrowth: -0.4, inflation: 0.4 },
    playerApprovalEffect: -3,
  },
  {
    id: 'unemployment-drop',
    category: 'economic_shock',
    title: 'Unemployment Falls to a Multi-Year Low',
    description: 'A strong hiring season pushes the jobless rate down sharply.',
    baseWeight: 3,
    economyEffect: { unemployment: -0.6, gdpGrowth: 0.3 },
    playerApprovalEffect: 5,
  },
  {
    id: 'credit-downgrade',
    category: 'economic_shock',
    title: 'Credit Rating Agency Issues a Warning',
    description: 'A ratings agency flags rising debt levels as a risk to the outlook.',
    baseWeight: 2,
    economyEffect: { budgetBalance: -0.3 },
    playerApprovalEffect: -3,
  },
  {
    id: 'coastal-storm',
    category: 'natural_disaster',
    title: 'Major Storm Batters the Coastline',
    description: 'A powerful storm system knocks out power and damages coastal towns.',
    baseWeight: 4,
    economyEffect: { gdpGrowth: -0.6, budgetBalance: -0.5 },
    playerApprovalEffect: -5,
  },
  {
    id: 'landslide',
    category: 'natural_disaster',
    title: 'Landslide Cuts Off a Mountain Region',
    description: 'Heavy rainfall triggers a landslide that isolates several villages.',
    baseWeight: 2,
    economyEffect: { budgetBalance: -0.3 },
    playerApprovalEffect: -4,
  },
  {
    id: 'heatwave',
    category: 'natural_disaster',
    title: 'Record Heatwave Strains the Power Grid',
    description: 'Soaring temperatures push electricity demand to breaking point.',
    baseWeight: 3,
    economyEffect: { gdpGrowth: -0.3 },
    playerApprovalEffect: -3,
  },
  {
    id: 'bumper-harvest',
    category: 'natural_disaster',
    title: 'Bumper Harvest Eases Food Prices',
    description: 'An unusually favorable growing season brings food costs down.',
    baseWeight: 2,
    economyEffect: { inflation: -0.3, gdpGrowth: 0.2 },
    playerApprovalEffect: 3,
  },
  {
    id: 'volcanic-ash',
    category: 'natural_disaster',
    title: 'Volcanic Ash Disrupts Air Travel',
    description: 'Ash from a distant eruption grounds flights and snarls trade routes.',
    baseWeight: 1,
    economyEffect: { gdpGrowth: -0.3 },
    playerApprovalEffect: -2,
  },
  {
    id: 'embassy-standoff',
    category: 'international_incident',
    title: 'Embassy Standoff Sparks Diplomatic Row',
    description: 'A tense standoff at a foreign embassy draws international attention.',
    baseWeight: 3,
    foreignRelationEffect: { counterpartId: 'nordholm', delta: -10 },
    playerApprovalEffect: -2,
  },
  {
    id: 'refugee-crisis',
    category: 'international_incident',
    title: 'Refugee Crisis Tests Border Capacity',
    description: 'A surge of refugees from a neighboring conflict strains resources.',
    baseWeight: 3,
    economyEffect: { budgetBalance: -0.4 },
    playerApprovalEffect: -3,
  },
  {
    id: 'trade-mission-success',
    category: 'international_incident',
    title: 'Trade Mission Lands Major Deal',
    description: 'A trade delegation returns home with a landmark export agreement.',
    baseWeight: 3,
    foreignRelationEffect: { counterpartId: 'valcressa', delta: 10 },
    economyEffect: { gdpGrowth: 0.4 },
    playerApprovalEffect: 3,
  },
  {
    id: 'espionage-scandal',
    category: 'international_incident',
    title: 'Foreign Espionage Ring Uncovered',
    description: 'Intelligence services announce the breakup of a foreign spy network.',
    baseWeight: 2,
    foreignRelationEffect: { counterpartId: 'suvenya', delta: -15 },
    playerApprovalEffect: 2,
  },
  {
    id: 'cultural-exchange',
    category: 'international_incident',
    title: 'Cultural Exchange Program Launches',
    description: 'A new student and artist exchange program strengthens ties abroad.',
    baseWeight: 2,
    foreignRelationEffect: { counterpartId: 'draventia', delta: 8 },
    playerApprovalEffect: 2,
  },
  {
    id: 'farmer-blockade',
    category: 'civil_unrest',
    title: "Farmers' Blockade Snarls Highways",
    description: 'Farmers block major roads to protest falling commodity prices.',
    baseWeight: 3,
    economyEffect: { gdpGrowth: -0.2 },
    playerApprovalEffect: -4,
  },
  {
    id: 'transit-strike',
    category: 'civil_unrest',
    title: 'Transit Workers Walk Off the Job',
    description: 'A citywide transit strike leaves commuters stranded for days.',
    baseWeight: 3,
    economyEffect: { gdpGrowth: -0.3 },
    playerApprovalEffect: -5,
  },
  {
    id: 'unity-rally',
    category: 'civil_unrest',
    title: 'Unity Rally Draws Record Crowds',
    description: 'A peaceful national unity rally draws praise across the political spectrum.',
    baseWeight: 2,
    playerApprovalEffect: 4,
  },
  {
    id: 'tenant-sit-in',
    category: 'civil_unrest',
    title: 'Tenants Stage Rent Sit-In',
    description: 'Renters occupy a city hall lobby demanding action on housing costs.',
    baseWeight: 2,
    playerApprovalEffect: -3,
  },
  {
    id: 'contamination-scare',
    category: 'public_health',
    title: 'Water Contamination Scare',
    description: 'Elevated contaminant levels are found in a regional water supply.',
    baseWeight: 3,
    economyEffect: { budgetBalance: -0.3 },
    playerApprovalEffect: -5,
  },
  {
    id: 'mental-health-initiative',
    category: 'public_health',
    title: 'National Mental Health Initiative Praised',
    description: 'A new counseling access program draws bipartisan praise.',
    baseWeight: 2,
    economyEffect: { budgetBalance: -0.2 },
    playerApprovalEffect: 4,
  },
  {
    id: 'food-safety-recall',
    category: 'public_health',
    title: 'Major Food Safety Recall',
    description: 'Regulators order a nationwide recall after a contamination outbreak.',
    baseWeight: 2,
    playerApprovalEffect: -3,
  },
  {
    id: 'life-expectancy-milestone',
    category: 'public_health',
    title: 'Life Expectancy Hits a New High',
    description: 'New health data shows life expectancy climbing for the third year running.',
    baseWeight: 1,
    playerApprovalEffect: 3,
  },
  {
    id: 'smuggling-ring-busted',
    category: 'security_incident',
    title: 'Cross-Border Smuggling Ring Busted',
    description: 'A joint operation dismantles a major smuggling network.',
    baseWeight: 2,
    playerApprovalEffect: 3,
  },
  {
    id: 'infrastructure-sabotage',
    category: 'security_incident',
    title: 'Sabotage Suspected in Power Outage',
    description: 'Investigators probe a suspicious outage at a major power substation.',
    baseWeight: 2,
    economyEffect: { budgetBalance: -0.3 },
    playerApprovalEffect: -4,
  },
  {
    id: 'data-breach',
    category: 'security_incident',
    title: 'Citizen Data Breach Exposed',
    description: 'A breach at a government contractor exposes citizens\' personal data.',
    baseWeight: 3,
    playerApprovalEffect: -6,
  },
  {
    id: 'expense-scandal',
    category: 'scandal',
    title: 'Lawmaker Expense Scandal Erupts',
    description: 'Records reveal lavish personal spending charged to the public purse.',
    baseWeight: 3,
    playerApprovalEffect: -6,
  },
  {
    id: 'ghostwriter-scandal',
    category: 'scandal',
    title: "Speech Ghostwriting Deal Raises Eyebrows",
    description: 'A paid ghostwriting arrangement with a donor draws ethics scrutiny.',
    baseWeight: 2,
    playerApprovalEffect: -4,
  },
  {
    id: 'whistleblower-praised',
    category: 'scandal',
    title: 'Whistleblower Praised for Exposing Waste',
    description: 'A government whistleblower is publicly commended after exposing wasteful spending.',
    baseWeight: 2,
    economyEffect: { budgetBalance: 0.2 },
    playerApprovalEffect: 3,
  },
];
