import type { CrisisEventDef } from '../../engine/systems/events';

/**
 * The base weighted event table. Actual per-turn weights are adjusted
 * against live game state by engine/systems/events.ts (a fragile economy
 * raises economic_shock odds, an unresolved scandal raises scandal odds,
 * low approval raises civil_unrest odds).
 */
export const CRISIS_TABLE: CrisisEventDef[] = [
  {
    id: 'recession-warning',
    category: 'economic_shock',
    title: 'Recession Warning',
    description: 'Economists warn of a coming downturn as growth stalls.',
    baseWeight: 6,
    economyEffect: { gdpGrowth: -0.8, unemployment: 0.5 },
    playerApprovalEffect: -5,
  },
  {
    id: 'market-rally',
    category: 'economic_shock',
    title: 'Surprise Market Rally',
    description: 'A wave of investor confidence sends markets higher.',
    baseWeight: 4,
    economyEffect: { gdpGrowth: 0.6 },
    playerApprovalEffect: 3,
  },
  {
    id: 'flooding',
    category: 'natural_disaster',
    title: 'Severe Flooding',
    description: 'Heavy rains flood the river delta, displacing thousands.',
    baseWeight: 5,
    economyEffect: { gdpGrowth: -0.5, budgetBalance: -0.4 },
    playerApprovalEffect: -4,
  },
  {
    id: 'earthquake',
    category: 'natural_disaster',
    title: 'Earthquake Strikes the Coast',
    description: 'A moderate earthquake damages infrastructure along the coast.',
    baseWeight: 3,
    economyEffect: { gdpGrowth: -0.7, budgetBalance: -0.6 },
    playerApprovalEffect: -6,
  },
  {
    id: 'border-incident',
    category: 'international_incident',
    title: 'Border Skirmish',
    description: 'Tensions flare after a border patrol confrontation.',
    baseWeight: 4,
    foreignRelationEffect: { counterpartId: 'nordholm', delta: -15 },
    playerApprovalEffect: -3,
  },
  {
    id: 'diplomatic-breakthrough',
    category: 'international_incident',
    title: 'Diplomatic Breakthrough',
    description: 'A surprise summit produces a goodwill agreement.',
    baseWeight: 3,
    foreignRelationEffect: { counterpartId: 'valcressa', delta: 12 },
    playerApprovalEffect: 4,
  },
  {
    id: 'general-strike',
    category: 'civil_unrest',
    title: 'General Strike',
    description: 'Unions call a nationwide strike over stagnant wages.',
    baseWeight: 5,
    economyEffect: { gdpGrowth: -0.4 },
    playerApprovalEffect: -6,
  },
  {
    id: 'street-protests',
    category: 'civil_unrest',
    title: 'Street Protests',
    description: 'Demonstrators gather in the capital demanding reform.',
    baseWeight: 5,
    playerApprovalEffect: -8,
  },
  {
    id: 'flu-outbreak',
    category: 'public_health',
    title: 'Seasonal Flu Outbreak',
    description: 'A severe flu season strains hospitals nationwide.',
    baseWeight: 4,
    economyEffect: { unemployment: 0.3, gdpGrowth: -0.2 },
    playerApprovalEffect: -3,
  },
  {
    id: 'vaccine-success',
    category: 'public_health',
    title: 'Vaccination Drive Succeeds',
    description: 'A national vaccination campaign exceeds its targets.',
    baseWeight: 3,
    playerApprovalEffect: 5,
  },
  {
    id: 'cyber-attack',
    category: 'security_incident',
    title: 'Cyberattack on Government Systems',
    description: "Hackers breach a government ministry's network.",
    baseWeight: 4,
    economyEffect: { budgetBalance: -0.3 },
    playerApprovalEffect: -5,
  },
  {
    id: 'foiled-plot',
    category: 'security_incident',
    title: 'Security Services Foil Plot',
    description: 'Intelligence services announce a foiled attack.',
    baseWeight: 3,
    playerApprovalEffect: 4,
  },
  {
    id: 'press-leak',
    category: 'scandal',
    title: 'Leaked Documents Raise Questions',
    description: 'A leaked memo raises fresh questions about government dealings.',
    baseWeight: 3,
    playerApprovalEffect: -6,
  },
];
