import type { CrisisEventDef } from '../../engine/systems/events';

/**
 * The base weighted event table. Actual per-turn weights are adjusted
 * against live game state by engine/systems/events.ts (a fragile economy
 * raises economic_shock odds, an unresolved scandal raises scandal odds,
 * low approval raises civil_unrest odds).
 */
export const CRISIS_TABLE: CrisisEventDef[] = [
  {
    id: 'recession-warning',
    category: 'economic_shock',
    title: 'Recession Warning',
    description: 'Economists warn of a coming downturn as growth stalls.',
    baseWeight: 6,
    economyEffect: { gdpGrowth: -0.8, unemployment: 0.5 },
    playerApprovalEffect: -5,
  },
  {
    id: 'market-rally',
    category: 'economic_shock',
    title: 'Surprise Market Rally',
    description: 'A wave of investor confidence sends markets higher.',
    baseWeight: 4,
    economyEffect: { gdpGrowth: 0.6 },
    playerApprovalEffect: 3,
  },
  {
    id: 'flooding',
    category: 'natural_disaster',
    title: 'Severe Flooding',
    description: 'Heavy rains flood the river delta, displacing thousands.',
    baseWeight: 5,
    economyEffect: { gdpGrowth: -0.5, budgetBalance: -0.4 },
    playerApprovalEffect: -4,
  },
  {
    id: 'earthquake',
    category: 'natural_disaster',
    title: 'Earthquake Strikes the Coast',
    description: 'A moderate earthquake damages infrastructure along the coast.',
    baseWeight: 3,
    economyEffect: { gdpGrowth: -0.7, budgetBalance: -0.6 },
    playerApprovalEffect: -6,
  },
  {
    id: 'border-incident',
    category: 'international_incident',
    title: 'Border Skirmish',
    description: 'Tensions flare after a border patrol confrontation.',
    baseWeight: 4,
    foreignRelationEffect: { counterpartId: 'nordholm', delta: -15 },
    playerApprovalEffect: -3,
  },
  {
    id: 'diplomatic-breakthrough',
    category: 'international_incident',
    title: 'Diplomatic Breakthrough',
    description: 'A surprise summit produces a goodwill agreement.',
    baseWeight: 3,
    foreignRelationEffect: { counterpartId: 'valcressa', delta: 12 },
    playerApprovalEffect: 4,
  },
  {
    id: 'general-strike',
    category: 'civil_unrest',
    title: 'General Strike',
    description: 'Unions call a nationwide strike over stagnant wages.',
    baseWeight: 5,
    economyEffect: { gdpGrowth: -0.4 },
    playerApprovalEffect: -6,
  },
  {
    id: 'street-protests',
    category: 'civil_unrest',
    title: 'Street Protests',
    description: 'Demonstrators gather in the capital demanding reform.',
    baseWeight: 5,
    playerApprovalEffect: -8,
  },
  {
    id: 'flu-outbreak',
    category: 'public_health',
    title: 'Seasonal Flu Outbreak',
    description: 'A severe flu season strains hospitals nationwide.',
    baseWeight: 4,
    economyEffect: { unemployment: 0.3, gdpGrowth: -0.2 },
    playerApprovalEffect: -3,
  },
  {
    id: 'vaccine-success',
    category: 'public_health',
    title: 'Vaccination Drive Succeeds',
    description: 'A national vaccination campaign exceeds its targets.',
    baseWeight: 3,
    playerApprovalEffect: 5,
  },
  {
    id: 'cyber-attack',
    category: 'security_incident',
    title: 'Cyberattack on Government Systems',
    description: "Hackers breach a government ministry's network.",
    baseWeight: 4,
    economyEffect: { budgetBalance: -0.3 },
    playerApprovalEffect: -5,
  },
  {
    id: 'foiled-plot',
    category: 'security_incident',
    title: 'Security Services Foil Plot',
    description: 'Intelligence services announce a foiled attack.',
    baseWeight: 3,
    playerApprovalEffect: 4,
  },
  {
    id: 'press-leak',
    category: 'scandal',
    title: 'Leaked Documents Raise Questions',
    description: 'A leaked memo raises fresh questions about government dealings.',
    baseWeight: 3,
    playerApprovalEffect: -6,
  },
  {
    id: 'currency-swings',
    category: 'economic_shock',
    title: 'Currency Volatility Rattles Markets',
    description: 'Sharp swings in the exchange rate unsettle importers and exporters alike.',
    baseWeight: 3,
    economyEffect: { inflation: 0.5, gdpGrowth: -0.2 },
    playerApprovalEffect: -2,
  },
  {
    id: 'export-contract',
    category: 'economic_shock',
    title: 'Major Export Contract Signed',
    description: 'A landmark export deal promises a boost to manufacturing.',
    baseWeight: 3,
    economyEffect: { gdpGrowth: 0.5, budgetBalance: 0.2 },
    playerApprovalEffect: 3,
  },
  {
    id: 'drought',
    category: 'natural_disaster',
    title: 'Prolonged Drought Hits Agriculture',
    description: 'A dry season strains farming regions and pushes up food prices.',
    baseWeight: 4,
    economyEffect: { inflation: 0.4, gdpGrowth: -0.3 },
    playerApprovalEffect: -4,
  },
  {
    id: 'wildfires',
    category: 'natural_disaster',
    title: 'Wildfires Sweep Rural Districts',
    description: 'Fast-moving wildfires force evacuations across several districts.',
    baseWeight: 3,
    economyEffect: { budgetBalance: -0.5 },
    playerApprovalEffect: -5,
  },
  {
    id: 'trade-dispute',
    category: 'international_incident',
    title: 'Trade Dispute Escalates',
    description: 'Tariff threats sour relations with a key trading partner.',
    baseWeight: 3,
    foreignRelationEffect: { counterpartId: 'suvenya', delta: -12 },
    economyEffect: { gdpGrowth: -0.2 },
    playerApprovalEffect: -2,
  },
  {
    id: 'joint-exercise',
    category: 'international_incident',
    title: 'Joint Military Exercise Praised',
    description: 'A successful joint exercise strengthens ties with an ally.',
    baseWeight: 2,
    foreignRelationEffect: { counterpartId: 'draventia', delta: 10 },
    playerApprovalEffect: 2,
  },
  {
    id: 'campus-protests',
    category: 'civil_unrest',
    title: 'University Campuses Erupt in Protest',
    description: 'Students walk out over tuition and cost-of-living concerns.',
    baseWeight: 3,
    playerApprovalEffect: -4,
  },
  {
    id: 'community-mediation',
    category: 'civil_unrest',
    title: 'Community Mediation Defuses Tensions',
    description: 'Local leaders broker a truce after weeks of unrest.',
    baseWeight: 2,
    playerApprovalEffect: 3,
  },
  {
    id: 'hospital-crisis',
    category: 'public_health',
    title: 'Hospital Overcrowding Crisis',
    description: 'Emergency rooms nationwide report dangerous overcrowding.',
    baseWeight: 3,
    economyEffect: { budgetBalance: -0.3 },
    playerApprovalEffect: -5,
  },
  {
    id: 'medical-breakthrough',
    category: 'public_health',
    title: 'Researchers Announce Medical Breakthrough',
    description: 'A domestic research team publishes a widely praised treatment advance.',
    baseWeight: 2,
    playerApprovalEffect: 4,
  },
  {
    id: 'arms-seizure',
    category: 'security_incident',
    title: 'Major Arms Seizure at the Border',
    description: 'Customs agents intercept a large illegal arms shipment.',
    baseWeight: 3,
    playerApprovalEffect: 3,
  },
  {
    id: 'prison-unrest',
    category: 'security_incident',
    title: 'Unrest Reported at a Major Prison',
    description: 'Overcrowding sparks a standoff at a national penitentiary.',
    baseWeight: 2,
    economyEffect: { budgetBalance: -0.2 },
    playerApprovalEffect: -3,
  },
  {
    id: 'donor-scandal',
    category: 'scandal',
    title: 'Undisclosed Donor Ties Revealed',
    description: 'Reporters uncover an undisclosed financial relationship with a major donor.',
    baseWeight: 3,
    playerApprovalEffect: -7,
  },
  {
    id: 'nepotism-claims',
    category: 'scandal',
    title: 'Nepotism Claims Rock a Ministry',
    description: 'A ministry is accused of steering appointments to well-connected relatives.',
    baseWeight: 2,
    playerApprovalEffect: -5,
  },
];
