import type { DilemmaDef } from '../../engine/models/types';

/**
 * The dilemma table — pre-authored, branching-choice crisis situations
 * (see engine/systems/dilemmas.ts). Weighted and triggered the same way as
 * CRISIS_TABLE's passive events, but the player picks the response instead
 * of it auto-applying. Every choice's numbers are pitched at the same
 * scale as CRISIS_TABLE's effects — a deliberate decision, not a bigger
 * lever than the rest of the game.
 */
export const DILEMMA_TABLE: DilemmaDef[] = [
  {
    id: 'factory-closures',
    category: 'economic_shock',
    title: 'Factory Closures Threaten a Region',
    description: 'A wave of manufacturing layoffs is about to hit a single region hard. Voters there are watching for a response.',
    baseWeight: 4,
    choices: [
      {
        id: 'bailout',
        label: 'Emergency Bailout',
        description: 'Prop up the plants with public money to save the jobs.',
        economyEffect: { budgetBalance: -0.6 },
        playerApprovalEffect: 6,
        delayedEconomyEffect: { turnsRemaining: 4, delta: { gdpGrowth: 0.3 } },
      },
      {
        id: 'let-it-correct',
        label: 'Let the Market Correct',
        description: 'Let the closures happen and let workers retrain elsewhere.',
        economyEffect: { budgetBalance: 0.2 },
        playerApprovalEffect: -7,
        delayedEconomyEffect: { turnsRemaining: 4, delta: { unemployment: 0.4 } },
      },
    ],
  },
  {
    id: 'inflation-spike',
    category: 'economic_shock',
    title: 'Inflation Spikes Unexpectedly',
    description: 'A sudden run-up in prices is eating into household budgets faster than forecasters expected.',
    baseWeight: 4,
    choices: [
      {
        id: 'tighten',
        label: 'Order a Rate Tightening',
        description: 'Cool the economy down to bring prices back under control.',
        economyEffect: { inflation: -0.7, gdpGrowth: -0.3 },
        playerApprovalEffect: -3,
      },
      {
        id: 'price-controls',
        label: 'Impose Price Controls',
        description: 'Cap prices on essentials directly, popular now, risky later.',
        economyEffect: { inflation: -0.9 },
        playerApprovalEffect: 5,
        delayedEconomyEffect: { turnsRemaining: 5, delta: { gdpGrowth: -0.4 } },
      },
    ],
  },
  {
    id: 'employer-relocation',
    category: 'economic_shock',
    title: 'Major Employer Threatens to Relocate Overseas',
    description: 'The country’s largest private employer says it may move its headquarters abroad unless terms improve.',
    baseWeight: 3,
    choices: [
      {
        id: 'tax-incentives',
        label: 'Offer Tax Incentives to Stay',
        description: 'Cut their tax bill to keep the jobs at home.',
        economyEffect: { budgetBalance: -0.4 },
        playerApprovalEffect: -2,
        delayedEconomyEffect: { turnsRemaining: 4, delta: { gdpGrowth: 0.4 } },
      },
      {
        id: 'let-them-go',
        label: 'Let Them Go',
        description: 'Refuse to bend the tax code for one company.',
        playerApprovalEffect: -4,
        delayedEconomyEffect: { turnsRemaining: 4, delta: { gdpGrowth: -0.3, unemployment: 0.3 } },
      },
    ],
  },
  {
    id: 'hurricane-approach',
    category: 'natural_disaster',
    title: 'Hurricane Approaches the Coast',
    description: 'Forecasters are tracking a major storm on a path toward densely populated coastal districts.',
    baseWeight: 4,
    choices: [
      {
        id: 'mandatory-evacuation',
        label: 'Order Mandatory Evacuation',
        description: 'Move people out by force of law, at real logistical cost.',
        economyEffect: { budgetBalance: -0.5 },
        playerApprovalEffect: 5,
      },
      {
        id: 'advisory-only',
        label: 'Advise but Don’t Mandate',
        description: 'Issue warnings and let people decide for themselves.',
        playerApprovalEffect: -6,
        delayedEconomyEffect: { turnsRemaining: 3, delta: { budgetBalance: -0.5 } },
      },
    ],
  },
  {
    id: 'wildfire-threat',
    category: 'natural_disaster',
    title: 'Wildfire Threatens Rural Towns',
    description: 'A fast-moving wildfire is closing in on several rural communities.',
    baseWeight: 3,
    choices: [
      {
        id: 'full-response',
        label: 'Deploy Full Firefighting Response',
        description: 'Commit every available crew and aircraft now.',
        economyEffect: { budgetBalance: -0.4 },
        playerApprovalEffect: 4,
      },
      {
        id: 'contain-and-monitor',
        label: 'Contain and Monitor',
        description: 'Hold a defensive line and let it burn out naturally.',
        playerApprovalEffect: -3,
        delayedEconomyEffect: { turnsRemaining: 3, delta: { budgetBalance: -0.6, gdpGrowth: -0.2 } },
      },
    ],
  },
  {
    id: 'earthquake-aftershocks',
    category: 'natural_disaster',
    title: 'Earthquake Aftershocks Continue',
    description: 'Days after the initial quake, aftershocks keep hampering recovery efforts.',
    baseWeight: 3,
    choices: [
      {
        id: 'national-emergency',
        label: 'Declare a National Emergency',
        description: 'Unlock full federal resources for the recovery.',
        economyEffect: { budgetBalance: -0.5 },
        playerApprovalEffect: 6,
        delayedEconomyEffect: { turnsRemaining: 4, delta: { gdpGrowth: 0.2 } },
      },
      {
        id: 'local-handles-it',
        label: 'Let Local Governments Handle It',
        description: 'Keep the response local and save the national budget.',
        economyEffect: { budgetBalance: 0.2 },
        playerApprovalEffect: -5,
      },
    ],
  },
  {
    id: 'military-aid-request',
    category: 'international_incident',
    title: 'Neighboring Nation Requests Military Aid',
    description: 'An allied government under pressure asks for arms and advisors.',
    baseWeight: 3,
    choices: [
      {
        id: 'send-support',
        label: 'Send Support',
        description: 'Commit real material aid to the ally.',
        economyEffect: { budgetBalance: -0.4 },
        foreignRelationEffect: { counterpartId: 'nordholm', delta: 15 },
        playerApprovalEffect: -1,
      },
      {
        id: 'stay-neutral',
        label: 'Stay Neutral',
        description: 'Decline to get involved in someone else’s conflict.',
        foreignRelationEffect: { counterpartId: 'nordholm', delta: -8 },
        playerApprovalEffect: 2,
      },
    ],
  },
  {
    id: 'spy-ring-uncovered',
    category: 'international_incident',
    title: 'Foreign Spy Ring Uncovered',
    description: 'Intelligence services confirm a foreign spy ring has been operating inside a government ministry.',
    baseWeight: 3,
    choices: [
      {
        id: 'expel-publicly',
        label: 'Expel Diplomats Publicly',
        description: 'Send a loud, unambiguous message.',
        foreignRelationEffect: { counterpartId: 'valcressa', delta: -20 },
        playerApprovalEffect: 7,
      },
      {
        id: 'quiet-channels',
        label: 'Handle It Through Back Channels',
        description: 'Resolve it quietly to preserve the relationship.',
        foreignRelationEffect: { counterpartId: 'valcressa', delta: -5 },
        playerApprovalEffect: -2,
      },
    ],
  },
  {
    id: 'refugee-crisis',
    category: 'international_incident',
    title: 'Refugee Crisis at the Border',
    description: 'Conflict abroad is sending a large wave of people toward the border seeking asylum.',
    baseWeight: 3,
    choices: [
      {
        id: 'open-border',
        label: 'Open the Border',
        description: 'Admit and process the arrivals.',
        economyEffect: { budgetBalance: -0.3 },
        foreignRelationEffect: { counterpartId: 'suvenya', delta: 10 },
        playerApprovalEffect: -3,
      },
      {
        id: 'reinforce-controls',
        label: 'Reinforce Border Controls',
        description: 'Turn back new arrivals and tighten enforcement.',
        economyEffect: { budgetBalance: -0.2 },
        foreignRelationEffect: { counterpartId: 'suvenya', delta: -10 },
        playerApprovalEffect: 3,
      },
    ],
  },
  {
    id: 'public-sector-strike-threat',
    category: 'civil_unrest',
    title: 'Public Sector Workers Threaten to Strike',
    description: 'Unions representing nurses and teachers threaten a walkout over stagnant pay.',
    baseWeight: 4,
    choices: [
      {
        id: 'grant-demands',
        label: 'Grant Their Demands',
        description: 'Fund the raise and avoid the walkout.',
        economyEffect: { budgetBalance: -0.5 },
        playerApprovalEffect: 6,
      },
      {
        id: 'hold-the-line',
        label: 'Hold the Line on Pay',
        description: 'Refuse the raise and risk the strike.',
        economyEffect: { budgetBalance: 0.2, gdpGrowth: -0.3 },
        playerApprovalEffect: -6,
      },
    ],
  },
  {
    id: 'student-protests',
    category: 'civil_unrest',
    title: 'Student Protests Escalate',
    description: 'Demonstrations outside the legislature have grown for a third straight day.',
    baseWeight: 4,
    choices: [
      {
        id: 'meet-leaders',
        label: 'Meet With Student Leaders',
        description: 'Sit down and hear them out publicly.',
        playerApprovalEffect: 4,
      },
      {
        id: 'clear-the-square',
        label: 'Deploy Police to Clear the Square',
        description: 'End the disruption by force.',
        playerApprovalEffect: -8,
        delayedEconomyEffect: { turnsRemaining: 3, delta: { gdpGrowth: -0.2 } },
      },
    ],
  },
  {
    id: 'farmer-blockade',
    category: 'civil_unrest',
    title: 'Farmers Blockade Major Highways',
    description: 'Farmers angry over falling crop prices have blocked several key highways with tractors.',
    baseWeight: 3,
    choices: [
      {
        id: 'raise-subsidies',
        label: 'Negotiate a Subsidy Increase',
        description: 'Buy peace with a real, ongoing budget commitment.',
        economyEffect: { budgetBalance: -0.4 },
        playerApprovalEffect: 5,
        delayedEconomyEffect: { turnsRemaining: 4, delta: { budgetBalance: -0.2 } },
      },
      {
        id: 'clear-by-force',
        label: 'Clear the Blockades by Force',
        description: 'End the disruption quickly and without new spending.',
        playerApprovalEffect: -5,
      },
    ],
  },
  {
    id: 'disease-strain',
    category: 'public_health',
    title: 'New Disease Strain Detected',
    description: 'Health authorities have identified a new, fast-spreading strain in a major city.',
    baseWeight: 4,
    choices: [
      {
        id: 'fund-response',
        label: 'Fund an Emergency Response',
        description: 'Move fast and spend heavily to contain it early.',
        economyEffect: { budgetBalance: -0.5 },
        playerApprovalEffect: 3,
        delayedEconomyEffect: { turnsRemaining: 4, delta: { gdpGrowth: 0.3 } },
      },
      {
        id: 'downplay',
        label: 'Downplay and Monitor',
        description: 'Avoid alarming the public and save the money for now.',
        economyEffect: { budgetBalance: 0.2 },
        delayedEconomyEffect: { turnsRemaining: 4, delta: { gdpGrowth: -0.5 } },
      },
    ],
  },
  {
    id: 'hospital-staffing-crisis',
    category: 'public_health',
    title: 'Hospital Staffing Crisis',
    description: 'Chronic understaffing is forcing hospitals to turn away non-emergency patients.',
    baseWeight: 3,
    choices: [
      {
        id: 'emergency-pay',
        label: 'Emergency Pay Boost for Staff',
        description: 'Spend now to retain and attract medical staff.',
        economyEffect: { budgetBalance: -0.4 },
        playerApprovalEffect: 5,
      },
      {
        id: 'import-staff',
        label: 'Recruit Temporary Foreign Staff',
        description: 'A cheaper fix that leans on an ally’s goodwill.',
        economyEffect: { budgetBalance: -0.15 },
        foreignRelationEffect: { counterpartId: 'draventia', delta: 6 },
        playerApprovalEffect: 2,
      },
    ],
  },
  {
    id: 'terror-plot-foiled',
    category: 'security_incident',
    title: 'Terror Plot Narrowly Foiled',
    description: 'Security services say they stopped an attack at the last moment and want expanded powers to prevent the next one.',
    baseWeight: 3,
    choices: [
      {
        id: 'expand-surveillance',
        label: 'Expand Surveillance Powers',
        description: 'Grant the new authority they’re asking for.',
        playerApprovalEffect: 3,
      },
      {
        id: 'reject-new-powers',
        label: 'Reassure the Public, Reject New Powers',
        description: 'Praise the agencies but decline to expand their authority.',
        playerApprovalEffect: 5,
      },
    ],
  },
  {
    id: 'base-security-breach',
    category: 'security_incident',
    title: 'Military Base Security Breach',
    description: 'An intruder breached perimeter security at a sensitive military installation overnight.',
    baseWeight: 3,
    choices: [
      {
        id: 'public-inquiry',
        label: 'Order a Full Public Inquiry',
        description: 'Air it out in the open, whatever it costs politically.',
        playerApprovalEffect: 4,
        delayedEconomyEffect: { turnsRemaining: 4, delta: { budgetBalance: -0.3 } },
      },
      {
        id: 'internal-review',
        label: 'Handle It With a Quiet Internal Review',
        description: 'Keep it out of the headlines and fix it internally.',
        playerApprovalEffect: -2,
      },
    ],
  },
  {
    id: 'minister-favoritism',
    category: 'scandal',
    title: 'Minister Accused of Favoritism',
    description: 'A cabinet minister is accused of steering contracts toward a family member’s firm.',
    baseWeight: 3,
    choices: [
      {
        id: 'demand-resignation',
        label: 'Demand Their Resignation',
        description: 'Cut them loose and get ahead of the story.',
        playerApprovalEffect: 5,
      },
      {
        id: 'stand-by-minister',
        label: 'Stand By Your Minister',
        description: 'Back them publicly and weather the criticism.',
        playerApprovalEffect: -6,
      },
    ],
  },
  {
    id: 'leaked-memo',
    category: 'scandal',
    title: 'Leaked Government Memo Sparks Controversy',
    description: 'A leaked internal memo appears to contradict public statements from your office.',
    baseWeight: 3,
    choices: [
      {
        id: 'full-transparency',
        label: 'Release Everything',
        description: 'Get the whole record out at once, however it looks.',
        playerApprovalEffect: -2,
        delayedEconomyEffect: { turnsRemaining: 3, delta: { gdpGrowth: 0.15 } },
      },
      {
        id: 'deny-and-deflect',
        label: 'Deny and Deflect',
        description: 'Dispute the memo’s authenticity and move on.',
        playerApprovalEffect: -5,
      },
    ],
  },
];
