import type { CorruptionTier } from '../../engine/models/types';

/** Pre-authored flavor text for each corruption tier's available actions. */
export const CORRUPTION_ACTIONS: Record<CorruptionTier, string[]> = {
  soft: [
    'Steer a minor contract to a loyal donor',
    'Leak a favorable talking point to a friendly reporter',
    'Grant a discreet committee favor',
    'Fast-track a permit for a well-connected constituent',
    'Quietly bump a supporter up the appointment waitlist',
    'Slip a friendly journalist an early copy of a report',
    'Comp a donor a seat at a high-profile event',
    'Overlook a minor filing error for an ally',
    'Recommend a supporter for a minor advisory board seat',
    'Quietly expedite a routine inspection for a friend',
    'Pass along a heads-up on an upcoming zoning change',
    'Arrange a courtesy meeting a donor wouldn\'t normally get',
  ],
  medium: [
    'Arrange a no-bid catering contract for a party backer',
    "Quietly waive a permitting fee for an ally's business",
    'Funnel a campaign donation through a shell PAC',
    "Steer a consulting contract to a relative's firm",
    'Trade a committee vote for a donor favor',
    'Award a lucrative signage contract to a campaign bundler',
    'Quietly kill an inconvenient audit',
    "Route a grant to a supporter's nonprofit",
    'Trade an ambassadorship nomination for a donation',
    'Lean on a regulator to go easy on a backer',
    'Pad a re-election war chest with a disguised in-kind donation',
    'Steer a land lease to a politically connected developer',
  ],
  hard: [
    'Accept a briefcase of cash for a zoning exemption',
    'Divert emergency relief funds to a shell company',
    'Rig a procurement bid for a kickback',
    'Sell a confidential floor-vote count to a lobbyist',
    'Launder a bribe through an offshore consultancy',
    'Extort a business owner for protection from regulators',
    'Sell classified briefing material to a foreign lobbyist',
    'Blackmail a rival with a manufactured scandal',
    'Skim funds from a disaster relief program',
    'Rig a state pension fund investment for a personal cut',
    'Take a bribe to bury a damaging investigation',
    'Sell a cabinet appointment to the highest bidder',
  ],
};
